### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by ikunsz666** [GZY-mingbai/ScreenInMC-Plugin#11]
下载了最新的ScreenInMC，[#5](https://github.com/GZY-mingbai/ScreenInMC-Plugin/issues/5)所描述的环境中，加载问题仍然出现，错误日志如下：

>}[07:22:54 WARN]: java.lang.UnsatisfiedLinkError: 'java.lang.String[] cn.mingbai.ScreenInMC.Natives.GPUDither.getPlatforms()'
�[07:22:54 WARN]:       at cn.mingbai.ScreenInMC.Natives.GPUDither.getPlatforms(Native Method)
[07:22:54 WARN]:        at cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.initImageUtils(ImageUtils.java:130)
�[07:22:54 WARN]:       at cn.mingbai.ScreenInMC.Main.onEnable(Main.java:200)
[07:22:54 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[07:22:54 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
�[07:22:54 WARN]:       at TRANSFORMER/forge@47.1.65/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:481)
~[07:22:54 WARN]:       at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:544)
�[07:22:54 WARN]:       at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:456)
[07:22:54 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:439)
{[07:22:54 WARN]:       at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:340)
�[07:22:54 WARN]:       at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:220)
:[07:22:54 WARN]:       at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:852)
[07:22:54 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:280)
[07:22:54 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
�[07:22:54 ERROR]: Error occurred while enabling ScreenInMC v2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "[Ljava.lang.String;.clone()" because "cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.platforms" is null
        at cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.getOpenCLPlatforms(ImageUtils.java:31) ~[ScreenInMC_2.jar:?]
        at cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.getBestOpenCLDevice(ImageUtils.java:42) ~[ScreenInMC_2.jar:?]
        at cn.mingbai.ScreenInMC.Main.onEnable(Main.java:219) ~[ScreenInMC_2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[forge-1.20.1-47.1.65-universal.jar%23226!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.1.65-universal.jar%23226!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:481) ~[forge-1.20.1-47.1.65-universal.jar%23226!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:544) ~[forge-1.20.1-47.1.65-universal.jar%23226!/:82af5dc6-e795d7490-3bce7935]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:456) ~[forge-1.20.1-47.1.65-universal.jar%23226!/:82af5dc6-e795d7490-3bce7935]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:439) ~[server-1.20.1-20230612.114412-srg.jar%23221!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:340) ~[server-1.20.1-20230612.114412-srg.jar%23221!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:220) ~[server-1.20.1-20230612.114412-srg.jar%23221!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:852) ~[server-1.20.1-20230612.114412-srg.jar%23221!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:280) ~[server-1.20.1-20230612.114412-srg.jar%23221!/:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
[07:22:54 INFO]: [ScreenInMC] Disabling ScreenInMC v2.0

**Comment by GZY-mingbai** [comment]
在提交(99b2921)中，我修复了该BUG，只需从GitHub Releases或蓝奏云重新下载即可

**Comment by ikunsz666** [comment]
显示web浏览器内核时出现汉字丢失问题，全是方框 如何解决

**Comment by GZY-mingbai** [comment]
在系统安装一个中文字体，并设置为默认

**Comment by ikunsz666** [comment]
面板服怎么办 可以让它手动加载一个字体文件吗 然后字体我来下载

**Comment by ikunsz666** [comment]
这个我就先关了...
