### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by acleverfreebird** [GZY-mingbai/ScreenInMC-Plugin#12]
![Screenshot_20230826_105122_com tungsten fcl](https://github.com/GZY-mingbai/ScreenInMC-Plugin/assets/122721335/bda967ad-60c4-4789-9218-48de125351c4)

**Comment by acleverfreebird** [comment]
全为方块字

**Comment by GZY-mingbai** [comment]
这个应该是因为你的jdk环境中没有支持中文的字体
你可以尝试安装一个中文字体 
或者在plugins/ScreenInMC/config.yml 将 language 改为 en_us

**Comment by acleverfreebird** [comment]
但我输入安装浏览器内核指令后，无法使用。

**Comment by GZY-mingbai** [comment]
GitHub上的readme目前没有更新，安装浏览器现在改到了网页浏览器核心中。
放置一块屏幕 将核心改成网页浏览器 就可以看到安装Chromium的按钮

**Comment by acleverfreebird** [comment]
点击后，没有任何提示，也没安装。
并且图片无法使用

**Comment by GZY-mingbai** [comment]
图片无法使用的话提供一下日志，以便修复BUG
无法安装可能是因为网络原因，无法连接至GitHub

**Comment by acleverfreebird** [comment]
[07:35:32] [Craft Scheduler Thread - 52 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.scaleImageAndGetPosition(ImageUtils.java:246)
[07:35:32] [Craft Scheduler Thread - 52 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.ImageViewer.updateImage(ImageViewer.java:216)
[07:35:32] [Craft Scheduler Thread - 52 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.ImageViewer.setEditGUISettingValue(ImageViewer.java:340)
[07:35:32] [Craft Scheduler Thread - 52 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1355)
[07:35:32] [Craft Scheduler Thread - 52 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[07:35:32] [Craft Scheduler Thread - 52 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[07:35:32] [Craft Scheduler Thread - 52 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:35:32] [Craft Scheduler Thread - 52 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:35:32] [Craft Scheduler Thread - 52 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:35:32] [Craft Scheduler Thread - 52 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[07:35:41] [Craft Scheduler Thread - 50 - ScreenInMC/WARN]: java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getWidth()" because "image" is null
[07:35:41] [Craft Scheduler Thread - 50 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.scaleImageAndGetPosition(ImageUtils.java:246)
[07:35:41] [Craft Scheduler Thread - 50 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.ImageViewer.updateImage(ImageViewer.java:216)
[07:35:41] [Craft Scheduler Thread - 50 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.ImageViewer.setEditGUISettingValue(ImageViewer.java:340)
[07:35:41] [Craft Scheduler Thread - 50 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1355)
[07:35:41] [Craft Scheduler Thread - 50 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[07:35:41] [Craft Scheduler Thread - 50 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[07:35:41] [Craft Scheduler Thread - 50 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:35:41] [Craft Scheduler Thread - 50 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:35:41] [Craft Scheduler Thread - 50 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:35:41] [Craft Scheduler Thread - 50 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by GZY-mingbai** [comment]
检查一下输入的图片URL是否正确，貌似是图片无法读取

**Comment by acleverfreebird** [comment]
[18:52:14] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:52:14] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:52:14] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:52:14] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:52:14] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:52:14] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:52:14] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:52:14] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:52:14] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:52:19] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:52:19] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:52:19] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:52:19] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:52:19] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:52:19] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:52:19] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:52:19] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:52:19] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:52:20] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:52:20] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:52:20] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:52:20] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:52:20] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:52:20] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:52:20] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:52:20] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:52:20] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:52:51] [Server thread/INFO]: free_bird issued server command: /screen browser 7271e7b5-5aa5-4d40-9a2a-432409f1e598 openurl
[18:52:56] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:52:56] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:52:56] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:52:56] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:52:56] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:52:56] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:52:56] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:52:56] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:52:56] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:53:03] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:53:03] [Craft Scheduler Thread - 29 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:53:08] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:53:08] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:53:08] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:53:08] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:53:08] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:53:08] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:53:08] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:53:08] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:53:08] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:53:12] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:53:12] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:53:12] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:53:12] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:53:12] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:53:12] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:53:12] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:53:12] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:53:12] [Craft Scheduler Thread - 32 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:53:13] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:53:13] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.installCore(Chromium.java:90)
[18:53:13] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser$6.run(WebBrowser.java:199)
[18:53:13] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:53:13] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:53:13] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:53:13] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:53:13] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:53:13] [Craft Scheduler Thread - 23 - ScreenInMC/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by acleverfreebird** [comment]
图片URL正确
为screen://local/1.png
此报错是安装浏览器的

**Comment by GZY-mingbai** [comment]
1.png应放置在plugins/ScreenInMC/Files中(并确保图片能够正常读取)
该报错貌似是因为配置文件中的system-type有误
![image](https://github.com/GZY-mingbai/ScreenInMC-Plugin/assets/42425278/9826b149-fc7b-47ec-ac4c-09a92665828f)

**Comment by acleverfreebird** [comment]
![Screenshot_20230826_192605_com microsoft emmx](https://github.com/GZY-mingbai/ScreenInMC-Plugin/assets/122721335/1ee37826-93aa-4200-88cc-9bcb4f376d17)
有没有问题，如果有，帮忙改正一下，谢谢大佬

**Comment by GZY-mingbai** [comment]
貌似是我这边代码有误
稍后我会修复这个问题
不过你也可以尝试将这里留空，让插件自动获取系统信息
