### ISSUE TITLE
创建第二个浏览器屏幕 无法修改帧数

### ISSUE THREAD

**Issue by 347180440** [GZY-mingbai/ScreenInMC-Plugin#13]
修改第一个创建的浏览器屏幕可以正常修改帧数。
【但是修改第二个浏览器屏幕 出现的报错】
14:39:28 WARN]: java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "cn.mingbai.ScreenInMC.Controller.EditGUI.getOpenedPlayer()" is null
[14:39:28 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.CommandListener.onCommand(CommandListener.java:276)
[14:39:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:39:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[14:39:28 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1017)
[14:39:28 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[14:39:28 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[14:39:28 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:332)
[14:39:28 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:316)
[14:39:28 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2392)
[14:39:28 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2352)
[14:39:28 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[14:39:28 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)[14:39:28 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:39:28 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:39:28 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:39:28 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1366)
[14:39:28 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[14:39:28 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:39:28 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1343)
[14:39:28 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1336)
[14:39:28 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:39:28 WARN]:        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1314)
[14:39:28 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[14:39:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[14:39:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:39:28 WARN]: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
[14:39:28 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Utils.CraftUtils.CraftUtils.getChannel(CraftUtils.java:311)
[14:39:28 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Utils.CraftUtils.CraftUtils.sendPacket(CraftUtils.java:315)
[14:39:28 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Controller.EditGUI.setBaseItems(EditGUI.java:2001)
[14:39:28 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Controller.EditGUI.access$2900(EditGUI.java:27)
[14:39:28 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1466)
[14:39:28 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:39:28 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:39:28 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:39:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:39:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:39:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:39:28 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
[14:39:28 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:561)
[14:39:28 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Utils.CraftUtils.CraftUtils.getChannel(CraftUtils.java:305)
[14:39:28 WARN]:        ... 10 more

**Comment by GZY-mingbai** [comment]
在提交(99b2921) 中，我修复了该BUG，只需从GitHub Releases或蓝奏云重新下载即可
