### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by ikunsz666** [GZY-mingbai/ScreenInMC-Plugin#14]
#5 的环境中，使用视频播放功能，控制台输出以下内容。
 #8 （同时复现了issue#8的问题）
错误日志：
[21:27:53 WARN]: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[], int, int)" because "inputStream" is null
[21:27:53 WARN]:        at cn.mingbai.ScreenInMC.VideoProcessor.readDitheredVideoWithPlugin(VideoProcessor.java:187)
[21:27:53 WARN]:        at cn.mingbai.ScreenInMC.BuiltInGUIs.VideoPlayer.play(VideoPlayer.java:118)
�[21:27:53 WARN]:       at cn.mingbai.ScreenInMC.BuiltInGUIs.VideoPlayer.setEditGUISettingValue(VideoPlayer.java:252)
[21:27:53 WARN]:        at cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1355)
[21:27:53 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78)
[21:27:53 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
[21:27:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:27:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:27:53 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[21:27:53 WARN]: Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[], int, int)" because "inputStream" is null
[21:27:53 WARN]:        at cn.mingbai.ScreenInMC.VideoProcessor.readDitheredVideo(VideoProcessor.java:239)
[21:27:53 WARN]:        at cn.mingbai.ScreenInMC.VideoProcessor.readDitheredVideoWithPlugin(VideoProcessor.java:167)
[21:27:53 WARN]:        ... 8 more
[21:27:53 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[], int, int)" because "inputStream" is null
[21:27:53 WARN]:        at cn.mingbai.ScreenInMC.VideoProcessor.readDitheredVideo(VideoProcessor.java:219)
[21:27:53 WARN]:        ... 9 more

**Comment by GZY-mingbai** [comment]
看上去好像是找不到文件

**Comment by ikunsz666** [comment]
不是找不到文件...文件正确的放在了plugins/ScreenInMC/Files/内，设置的地址也是正确的
>workspace/plugins/ScreenInMC/Files/output.smv
screen://local/output.smv

**Comment by GZY-mingbai** [comment]
检查一下文件权限，看一下日志里有没有FileInputStream 的报错
