### ISSUE TITLE
浏览器无法启动

### ISSUE THREAD

**Issue by ikunsz666** [GZY-mingbai/ScreenInMC-Plugin#15]
错误日志如下...
---

>[09:46:55 INFO]: [ScreenInMC] Load Chromium with args: --transparent-painting-disabled --disable-gpu --disable-gpu-compositing --disable-gpu-vsync --off-screen-rendering-enabled --off-screen-frame-rate=20 --universal-access-from-file-urls-allowed --no-sandbox 
�[09:46:55 WARN]: java.lang.UnsatisfiedLinkError: /workspace/plugins/ScreenInMC/Chromium/bin/lib/linux64/libcef.so: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
 [09:46:55 WARN]:       at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
[09:46:55 WARN]:        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
[09:46:55 WARN]:        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
�[09:46:55 WARN]:       at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
[09:46:55 WARN]:        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
[09:46:55 WARN]:        at java.base/java.lang.Runtime.load0(Unknown Source)
[09:46:55 WARN]:        at java.base/java.lang.System.load(Unknown Source)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.ChromiumLibrariesLoader$1.loadLibrary(ChromiumLibrariesLoader.java:43)
R[09:46:55 WARN]:       at org.cef.SystemBootstrap.loadLibrary(SystemBootstrap.java:36)
@[09:46:55 WARN]:       at org.cef.CefApp.<init>(CefApp.java:151)
[09:46:55 WARN]:        at org.cef.CefApp.getInstance(CefApp.java:221)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.load(Chromium.java:382)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.access$000(Chromium.java:263)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium.loadCore(Chromium.java:174)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.loadBrowser(WebBrowser.java:226)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.setEditGUISettingValue(WebBrowser.java:416)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1453)
[09:46:55 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78)
[09:46:55 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
[09:46:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[09:46:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[09:46:55 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[09:46:55 WARN]: java.lang.UnsatisfiedLinkError: no cef in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
[09:46:55 WARN]:        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
[09:46:55 WARN]:        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
[09:46:55 WARN]:        at java.base/java.lang.System.loadLibrary(Unknown Source)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.ChromiumLibrariesLoader$1.loadLibrary(ChromiumLibrariesLoader.java:48)
[09:46:55 WARN]:        at org.cef.SystemBootstrap.loadLibrary(SystemBootstrap.java:36)
[09:46:55 WARN]:        at org.cef.CefApp.<init>(CefApp.java:151)
A[09:46:55 WARN]:       at org.cef.CefApp.getInstance(CefApp.java:221)
_[09:46:55 WARN]:       at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.load(Chromium.java:382)
�[09:46:55 WARN]:       at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.access$000(Chromium.java:263)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium.loadCore(Chromium.java:174)
([09:46:55 WARN]:       at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.loadBrowser(WebBrowser.java:226)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.setEditGUISettingValue(WebBrowser.java:416)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1453)
z[09:46:55 WARN]:       at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78)
�[09:46:55 WARN]:       at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
[09:46:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[09:46:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[09:46:55 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
=[09:46:55 WARN]: java.lang.reflect.InvocationTargetException
�[09:46:55 WARN]:       at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
�[09:46:55 WARN]:       at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
[09:46:55 WARN]:        at org.cef.CefApp.<init>(CefApp.java:170)
[09:46:55 WARN]:        at org.cef.CefApp.getInstance(CefApp.java:221)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.load(Chromium.java:382)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.access$000(Chromium.java:263)
�[09:46:55 WARN]:       at cn.mingbai.ScreenInMC.Browsers.Chromium.loadCore(Chromium.java:174)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.loadBrowser(WebBrowser.java:226)
�[09:46:55 WARN]:       at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.setEditGUISettingValue(WebBrowser.java:416)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1453)
_[09:46:55 WARN]:       at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78)
[09:46:55 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
[09:46:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
b[09:46:55 WARN]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
D[09:46:55 WARN]:       at java.base/java.lang.Thread.run(Unknown Source)
/[09:46:55 WARN]: Caused by: java.lang.UnsatisfiedLinkError: 'boolean org.cef.CefApp.N_PreInitialize()'
[09:46:55 WARN]:        at org.cef.CefApp.N_PreInitialize(Native Method)
[09:46:55 WARN]:        at org.cef.CefApp$1.run(CefApp.java:163)
[09:46:55 WARN]:        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
b[09:46:55 WARN]:       at java.base/java.security.AccessController.doPrivileged(Unknown Source)
[09:46:55 WARN]:        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
---
>�[09:46:55 INFO]: initialize on Thread[AWT-EventQueue-0,6,main] with library path /workspace/plugins/ScreenInMC/Chromium/bin/lib/linux64
�[09:46:55 WARN]: java.lang.reflect.InvocationTargetException
[09:46:55 WARN]:        at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
N[09:46:55 WARN]:       at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
[09:46:55 WARN]:        at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
[09:46:55 WARN]:        at org.cef.CefApp.initialize(CefApp.java:433)
[09:46:55 WARN]:        at org.cef.CefApp.createClient(CefApp.java:315)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.load(Chromium.java:388)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.access$000(Chromium.java:263)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium.loadCore(Chromium.java:174)
�[09:46:55 WARN]:       at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.loadBrowser(WebBrowser.java:226)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.setEditGUISettingValue(WebBrowser.java:416)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1453)
[09:46:55 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78)
�[09:46:55 WARN]:       at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
a[09:46:55 WARN]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
b[09:46:55 WARN]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
D[09:46:55 WARN]:       at java.base/java.lang.Thread.run(Unknown Source)
[09:46:55 WARN]: Caused by: java.lang.UnsatisfiedLinkError: 'boolean org.cef.CefApp.N_Initialize(org.cef.handler.CefAppHandler, org.cef.CefSettings)'
[09:46:55 WARN]:        at org.cef.CefApp.N_Initialize(Native Method)
[09:46:55 WARN]:        at org.cef.CefApp$3.run(CefApp.java:427)
Z[09:46:55 WARN]:       at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
X[09:46:55 WARN]:       at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
p[09:46:55 WARN]:       at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
[09:46:55 WARN]:        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
[09:46:55 WARN]:        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
�[09:46:55 WARN]:       at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[09:46:55 WARN]:        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
Z[09:46:55 WARN]:       at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
S[09:46:55 WARN]:       at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
s[09:46:55 WARN]: java.lang.UnsatisfiedLinkError: 'void org.cef.handler.CefClientHandler.N_CefClientHandler_CTOR()'
�[09:46:55 WARN]:       at org.cef.handler.CefClientHandler.N_CefClientHandler_CTOR(Native Method)
[09:46:55 WARN]:        at org.cef.handler.CefClientHandler.<init>(CefClientHandler.java:39)
�[09:46:55 WARN]:       at org.cef.CefClient.<init>(CefClient.java:110)
[09:46:55 WARN]:        at org.cef.CefApp.createClient(CefApp.java:320)
_[09:46:55 WARN]:       at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.load(Chromium.java:388)
e[09:46:55 WARN]:       at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.access$000(Chromium.java:263)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium.loadCore(Chromium.java:174)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.loadBrowser(WebBrowser.java:226)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.setEditGUISettingValue(WebBrowser.java:416)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1453)
[09:46:55 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78)
[09:46:55 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
a[09:46:55 WARN]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
b[09:46:55 WARN]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
D[09:46:55 WARN]:       at java.base/java.lang.Thread.run(Unknown Source)
�[09:46:55 WARN]: java.lang.UnsatisfiedLinkError: 'boolean org.cef.CefApp.N_RegisterSchemeHandlerFactory(java.lang.String, java.lang.String, org.cef.callback.CefSchemeHandlerFactory)'
R[09:46:55 WARN]:       at org.cef.CefApp.N_RegisterSchemeHandlerFactory(Native Method)
R[09:46:55 WARN]:       at org.cef.CefApp.registerSchemeHandlerFactory(CefApp.java:345)
E[09:46:55 WARN]:       at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.load(Chromium.java:390)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.access$000(Chromium.java:263)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium.loadCore(Chromium.java:174)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.loadBrowser(WebBrowser.java:226)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.setEditGUISettingValue(WebBrowser.java:416)
[09:46:55 WARN]:        at cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1453)
[09:46:55 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78)
[09:46:55 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
[09:46:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[09:46:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[09:46:55 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
�[09:47:19 WARN]: java.lang.UnsatisfiedLinkError: /workspace/natives/linux-amd64/libnativewindow_x11.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
�[09:47:19 WARN]:       at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
[09:47:19 WARN]:        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
V[09:47:19 WARN]:       at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
[09:47:19 WARN]:        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
[09:47:19 WARN]:        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
[09:47:19 WARN]:        at java.base/java.lang.Runtime.load0(Unknown Source)
E[09:47:19 WARN]:       at java.base/java.lang.System.load(Unknown Source)
Q[09:47:19 WARN]:       at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
[09:47:19 WARN]:        at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
[09:47:19 WARN]:        at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
[09:47:19 WARN]:        at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
[09:47:19 WARN]:        at jogamp.nativewindow.NWJNILibLoader.access$000(NWJNILibLoader.java:39)
[09:47:19 WARN]:        at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:49)
g[09:47:19 WARN]:       at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:41)
[09:47:19 WARN]:        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
[09:47:19 WARN]:        at jogamp.nativewindow.NWJNILibLoader.loadNativeWindow(NWJNILibLoader.java:41)
[09:47:19 WARN]:        at jogamp.nativewindow.x11.X11Util.initSingleton(X11Util.java:122)
d[09:47:19 WARN]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
�[09:47:19 WARN]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:47:19 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
�[09:47:19 WARN]:       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[09:47:19 WARN]:        at com.jogamp.common.util.ReflectionUtil.callMethod(ReflectionUtil.java:417)
[09:47:19 WARN]:        at com.jogamp.common.util.ReflectionUtil.callStaticMethod(ReflectionUtil.java:439)
[09:47:19 WARN]:        at com.jogamp.nativewindow.NativeWindowFactory.initSingletonNativeImpl(NativeWindowFactory.java:294)
[09:47:19 WARN]:        at com.jogamp.nativewindow.NativeWindowFactory.initSingleton(NativeWindowFactory.java:449)
d[09:47:19 WARN]:       at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1742)
O[09:47:19 WARN]:       at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
M[09:47:19 WARN]:       at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:239)
[09:47:19 WARN]:        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
[09:47:19 WARN]:        at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:225)
[09:47:19 WARN]:        at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2324)
�[09:47:19 WARN]:       at com.jogamp.opengl.GLProfile.get(GLProfile.java:1042)
[09:47:19 WARN]:        at com.jogamp.opengl.GLProfile.get(GLProfile.java:1071)
[09:47:19 WARN]:        at com.jogamp.opengl.GLProfile.getMaxFixedFunc(GLProfile.java:824)
[09:47:19 WARN]:        at org.cef.browser.CefBrowserOsr.createGLCanvas(CefBrowserOsr.java:138)
[09:47:19 WARN]:        at org.cef.browser.CefBrowserOsr.<init>(CefBrowserOsr.java:96)
[09:47:19 WARN]:        at org.cef.browser.CefBrowserOsr.<init>(CefBrowserOsr.java:88)
[09:47:19 WARN]:        at org.cef.browser.ScreenInMCChromiumBrowser.<init>(ScreenInMCChromiumBrowser.java:54)
[09:47:19 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.createBrowser(Chromium.java:669)
[09:47:19 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.access$200(Chromium.java:263)
[09:47:19 WARN]:        at cn.mingbai.ScreenInMC.Browsers.Chromium.createBrowser(Chromium.java:200)
[09:47:19 WARN]:        at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.loadBrowser(WebBrowser.java:238)
[09:47:19 WARN]:        at cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.setEditGUISettingValue(WebBrowser.java:416)
[09:47:19 WARN]:        at cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1453)
[09:47:19 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78)
[09:47:19 WARN]:        at TRANSFORMER/forge@47.1.65/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
[09:47:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[09:47:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[09:47:19 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by GZY-mingbai** [comment]
系统缺少libgobject-2.0.so.0 (Chromium 的依赖库)
