### ISSUE TITLE
VNC屏幕卡着不动

### ISSUE THREAD

**Issue by innovateplus** [GZY-mingbai/ScreenInMC-Plugin#16]
点击连接后一直没有反应
日志：
[15:19:48 WARN]: com.shinyhut.vernacular.client.exceptions.UnexpectedVncException: An unexpected exception occurred: ConnectException
[15:19:48 WARN]:        at ScreenInMC.jar//com.shinyhut.vernacular.client.VernacularClient.start(VernacularClient.java:54)
[15:19:48 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.VNCClient.connectServer(VNCClient.java:173)
[15:19:48 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.VNCClient$1$1.run(VNCClient.java:74)
[15:19:48 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:19:48 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:19:48 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:19:48 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:19:48 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:19:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:19:48 WARN]: Caused by: java.net.ConnectException: Connection timed out: connect
[15:19:48 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[15:19:48 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
[15:19:48 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
[15:19:48 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
[15:19:48 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[15:19:48 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[15:19:48 WARN]:        at java.base/java.net.Socket.connect(Socket.java:583)
[15:19:48 WARN]:        at java.base/java.net.Socket.<init>(Socket.java:507)
[15:19:48 WARN]:        at java.base/java.net.Socket.<init>(Socket.java:287)
[15:19:48 WARN]:        at ScreenInMC.jar//com.shinyhut.vernacular.client.VernacularClient.start(VernacularClient.java:52)
[15:19:48 WARN]:        ... 8 more

**Comment by GZY-mingbai** [comment]
连接超时，检查 VNC 服务器是否正常

**Comment by innovateplus** [comment]
我想请问一下用什么软件搭建VNC服务器能正常连接啊？我试了RealVNC好像不行

**Comment by GZY-mingbai** [comment]
可能端口未开放？我演示是使用的TightVNC

**Comment by innovateplus** [comment]
![屏幕截图 2023-08-27 161624](https://github.com/GZY-mingbai/ScreenInMC-Plugin/assets/78544816/80bfc21d-8387-443e-85e5-e23dec6b89ba)
ok，安装了tightVNC，请问是这样的默认设置吗？还是在游戏内输入ip时要带端口号？

**Comment by GZY-mingbai** [comment]
不需要端口号，你可能需要在防火墙开放 5900 端口(tcp)

**Comment by innovateplus** [comment]
感谢！成功了
