### ISSUE TITLE
重启服务器屏幕出错

### ISSUE THREAD

**Issue by ZOHI666** [GZY-mingbai/ScreenInMC-Plugin#19]
重启服务器后所有屏幕变成透明，必须要删除屏幕后重新添加，直接点编辑会没有反应

**Comment by ZOHI666** [comment]
[Server thread/ERROR]: Could not pass event PlayerJoinEvent to ScreenInMC v2.0
java.lang.IllegalStateException: channel not registered to an event loop
	at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:164) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.executor(AbstractChannelHandlerContext.java:132) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.newPromise(AbstractChannelHandlerContext.java:995) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at cn.mingbai.ScreenInMC.Utils.CraftUtils.CraftUtils.sendPacket(CraftUtils.java:316) ~[ScreenInMC.jar:?]
	at cn.mingbai.ScreenInMC.Screen.Screen.sendView(Screen.java:343) ~[ScreenInMC.jar:?]
	at cn.mingbai.ScreenInMC.Screen.Screen.clearScreen(Screen.java:198) ~[ScreenInMC.jar:?]
	at cn.mingbai.ScreenInMC.Screen.Screen.clearScreen(Screen.java:184) ~[ScreenInMC.jar:?]
	at cn.mingbai.ScreenInMC.Core.reRender(Core.java:45) ~[ScreenInMC.jar:?]
	at cn.mingbai.ScreenInMC.Screen.Screen.sendPutScreenPacket(Screen.java:225) ~[ScreenInMC.jar:?]
	at cn.mingbai.ScreenInMC.EventListener.onPlayerJoin(EventListener.java:57) ~[ScreenInMC.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor913.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-58]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-58]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-58]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:339) ~[paper-1.20.1.jar:git-Paper-58]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1587) ~[paper-1.20.1.jar:git-Paper-58]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-58]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ZOHI666** [comment]
[Craft Scheduler Thread - 24 - ScreenInMC/WARN]: [ScreenInMC] Plugin ScreenInMC v2.0 generated an exception while executing task 150
java.lang.IllegalStateException: channel not registered to an event loop
	at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:164) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.executor(AbstractChannelHandlerContext.java:132) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.newPromise(AbstractChannelHandlerContext.java:995) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at cn.mingbai.ScreenInMC.Utils.CraftUtils.CraftUtils.sendPacket(CraftUtils.java:316) ~[ScreenInMC.jar:?]
	at cn.mingbai.ScreenInMC.Screen.Screen.sendView(Screen.java:354) ~[ScreenInMC.jar:?]
	at cn.mingbai.ScreenInMC.BuiltInGUIs.VideoPlayer$1.run(VideoPlayer.java:150) ~[ScreenInMC.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-58]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by 347180440** [comment]
原因在这里 #8  因为重启服务器时 配置文件没保存url选项 等待修复中
