### ISSUE TITLE
加载Chromium核心时出错

### ISSUE THREAD

**Issue by DrSmoothl** [GZY-mingbai/ScreenInMC-Plugin#27]
提示缺少JOGL
我该如何添加JOGL到我的服务器上

[18:46:46 WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
[18:46:46 WARN]:        at ScreenInMC.jar//org.cef.browser.CefBrowserOsr.createGLCanvas(CefBrowserOsr.java:138)
[18:46:46 WARN]:        at ScreenInMC.jar//org.cef.browser.CefBrowserOsr.<init>(CefBrowserOsr.java:96)
[18:46:46 WARN]:        at ScreenInMC.jar//org.cef.browser.CefBrowserOsr.<init>(CefBrowserOsr.java:88)
[18:46:46 WARN]:        at ScreenInMC.jar//org.cef.browser.ScreenInMCChromiumBrowser.<init>(ScreenInMCChromiumBrowser.java:54)
[18:46:46 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.createBrowser(Chromium.java:691)
[18:46:46 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.access$200(Chromium.java:260)
[18:46:46 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.createBrowser(Chromium.java:197)
[18:46:46 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.loadBrowser(WebBrowser.java:238)
[18:46:46 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.setEditGUISettingValue(WebBrowser.java:416)
[18:46:46 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1453)
[18:46:46 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[18:46:46 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:46:46 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:46:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:46:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:46:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:47:27 WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
[18:47:27 WARN]:        at ScreenInMC.jar//org.cef.browser.CefBrowserOsr.createGLCanvas(CefBrowserOsr.java:138)
[18:47:27 WARN]:        at ScreenInMC.jar//org.cef.browser.CefBrowserOsr.<init>(CefBrowserOsr.java:96)
[18:47:27 WARN]:        at ScreenInMC.jar//org.cef.browser.CefBrowserOsr.<init>(CefBrowserOsr.java:88)
[18:47:27 WARN]:        at ScreenInMC.jar//org.cef.browser.ScreenInMCChromiumBrowser.<init>(ScreenInMCChromiumBrowser.java:54)
[18:47:27 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.createBrowser(Chromium.java:691)
[18:47:27 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium$Chromium_.access$200(Chromium.java:260)
[18:47:27 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Browsers.Chromium.createBrowser(Chromium.java:197)
[18:47:27 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.loadBrowser(WebBrowser.java:238)
[18:47:27 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.BuiltInGUIs.WebBrowser.setEditGUISettingValue(WebBrowser.java:416)
[18:47:27 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Controller.EditGUI$2.run(EditGUI.java:1453)
[18:47:27 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[18:47:27 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:47:27 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:47:27 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:47:27 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:47:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by GZY-mingbai** [comment]
检查一下 Chromium 是否下载完全，不完全的话可以删除重下
