### ISSUE TITLE
在Paper1.20.6中加载失败

### ISSUE THREAD

**Issue by Steve3184** [GZY-mingbai/ScreenInMC-Plugin#37]
使用核心：Paper1.20.6-130

日志：
```
[13:04:21] [Server thread/INFO]: [ScreenInMC] Enabling ScreenInMC v2.0
[13:04:21] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredFields()" because "cn.mingbai.ScreenInMC.Utils.CraftUtils.CraftUtils.ConnectionClass" is null
[13:04:21] [Server thread/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Utils.CraftUtils.CraftUtils.init(CraftUtils.java:107)
[13:04:21] [Server thread/WARN]: 	at ScreenInMC.jar//cn.mingbai.ScreenInMC.Main.onEnable(Main.java:227)
[13:04:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[13:04:21] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[13:04:21] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[13:04:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[13:04:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604)
[13:04:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553)
[13:04:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[13:04:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[13:04:21] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323)
[13:04:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)
[13:04:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[13:04:21] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[13:04:21] [Server thread/WARN]: [ScreenInMC] ScreenInMC load failed.
```

**Comment by dsmng54** [comment]
Paper1.21-111也是这样

**Comment by GZY-mingbai** [comment]
目前插件仅支持到1.20.4

**Comment by GZY-mingbai** [comment]
最新版本 3a10895 已经支持了1.20.5-1.21.1
到 Releases 里下载最新版本即可
