### ISSUE TITLE
JVMCFRE003 主要版本错误；类=cn/mingbai/ScreenInMC/Main，偏移量=6

### ISSUE THREAD

**Issue by NeglectDream** [GZY-mingbai/ScreenInMC-Plugin#4]
你好，我看你介绍写的是Java8可以使用，但是经测试并不行，希望修复！
测试环境1.8.8paper+Java8
`
[08:30:43] [Server thread/ERROR]: Could not load 'plugins\[动态播放]ScreenInMC.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: JVMCFRE003 主要版本错误；类=cn/mingbai/ScreenInMC/Main，偏移量=6
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_282]
Caused by: java.lang.UnsupportedClassVersionError: JVMCFRE003 主要版本错误；类=cn/mingbai/ScreenInMC/Main，偏移量=6
	at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:1.8.0_282]
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398) ~[?:1.8.0_282]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359) ~[?:1.8.0_282]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_282]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682) ~[?:1.8.0_282]
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89) ~[?:1.8.0_282]
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086) ~[?:1.8.0_282]
	at java.security.AccessController.doPrivileged(AccessController.java:774) ~[?:1.8.0_282]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589) ~[?:1.8.0_282]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953) ~[?:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898) ~[?:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881) ~[?:1.8.0_282]
	at java.lang.Class.forNameImpl(Native Method) ~[?:1.8.0_282]
	at java.lang.Class.forName(Class.java:408) ~[?:1.8.0_282]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
`

**Comment by GZY-mingbai** [comment]
由于我这边忘记把GitHub Actions的编译任务的jdk版本改为8了，所以无法使用
目前我已经修改(e0a0de4)并上传了插件，
只需要在GitHub Releases或蓝奏云重新下载就行
