### ISSUE TITLE
Loading the plugin failed

### ISSUE THREAD

**Issue by 347180440** [GZY-mingbai/ScreenInMC-Plugin#6]
[20:05:19 INFO]: [ScreenInMC] Enabling ScreenInMC v2.0
[20:05:26 WARN]: java.lang.UnsatisfiedLinkError: 'java.lang.String[] cn.mingbai.ScreenInMC.Natives.GPUDither.getPlatforms()'
[20:05:26 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Natives.GPUDither.getPlatforms(Native Method)
[20:05:26 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.initImageUtils(ImageUtils.java:130)
[20:05:26 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Main.onEnable(Main.java:200)
[20:05:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[20:05:26 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[20:05:26 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[20:05:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[20:05:26 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:650)
[20:05:26 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:561)
[20:05:26 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[20:05:26 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440)
[20:05:26 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
[20:05:26 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
[20:05:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[20:05:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[20:05:26 ERROR]: Error occurred while enabling ScreenInMC v2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "[Ljava.lang.String;.clone()" because "cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.platforms" is null
        at cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.getOpenCLPlatforms(ImageUtils.java:31) ~[ScreenInMC.jar:?]
        at cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.getBestOpenCLDevice(ImageUtils.java:42) ~[ScreenInMC.jar:?]
        at cn.mingbai.ScreenInMC.Main.onEnable(Main.java:219) ~[ScreenInMC.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:650) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:561) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:05:26 INFO]: [ScreenInMC] Disabling ScreenInMC v2.0
[20:05:26 INFO]: Running delayed init tasks
[20:05:26 INFO]: Done (17.603s)! For help, type "help"
[20:05:26 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
> plugins
[20:05:38 INFO]: Bukkit Plugins: (5):
[20:05:38 INFO]:  - ScreenInMC, spark, ViaBackwards, ViaRewind, ViaVersion

> version
[20:07:19 INFO]: Checking version, please wait...
[20:07:21 INFO]: Current: git-Purpur-2001 (MC: 1.20.1)* 
> version
[20:23:41 INFO]: Checking version, please wait...
[20:23:43 INFO]: This server is running Paper version git-Paper-134 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 2bd6ba2)

**Comment by GZY-mingbai** [comment]
这个 BUG 应该已经在 #3 修复了，如果你是较早下载插件的话，可以尝试在蓝奏云或 GitHub Releases 中重新下载
