### ISSUE TITLE
无法加载插件，日志如下

### ISSUE THREAD

**Issue by innovateplus** [GZY-mingbai/ScreenInMC-Plugin#9]
[22:51:19 WARN]: java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\screen-in-mc-windows-amd6413616819600853095130.dll: Can't find dependent libraries
[22:51:19 WARN]:        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
[22:51:19 WARN]:        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
[22:51:19 WARN]:        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
[22:51:19 WARN]:        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
[22:51:19 WARN]:        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
[22:51:19 WARN]:        at java.base/java.lang.Runtime.load0(Runtime.java:755)
[22:51:19 WARN]:        at java.base/java.lang.System.load(System.java:1953)
[22:51:19 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Main.<clinit>(Main.java:57)
[22:51:19 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[22:51:19 WARN]:        at java.base/java.lang.Class.forName(Class.java:467)
[22:51:19 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[22:51:19 WARN]:        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123)
[22:51:19 WARN]:        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35)
[22:51:19 WARN]:        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116)
[22:51:19 WARN]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[22:51:19 WARN]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[22:51:19 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:508)
[22:51:19 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
[22:51:19 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[22:51:19 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[22:51:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:51:22 WARN]: java.lang.UnsatisfiedLinkError: 'java.lang.String[] cn.mingbai.ScreenInMC.Natives.GPUDither.getPlatforms()'
[22:51:22 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Natives.GPUDither.getPlatforms(Native Method)
[22:51:22 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.initImageUtils(ImageUtils.java:130)
[22:51:22 WARN]:        at ScreenInMC.jar//cn.mingbai.ScreenInMC.Main.onEnable(Main.java:200)
[22:51:22 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[22:51:22 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[22:51:22 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[22:51:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[22:51:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640)
[22:51:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551)
[22:51:22 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[22:51:22 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[22:51:22 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[22:51:22 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[22:51:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[22:51:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:51:22 ERROR]: Error occurred while enabling ScreenInMC v2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "[Ljava.lang.String;.clone()" because "cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.platforms" is null
        at cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.getOpenCLPlatforms(ImageUtils.java:31) ~[ScreenInMC.jar:?]
        at cn.mingbai.ScreenInMC.Utils.ImageUtils.ImageUtils.getBestOpenCLDevice(ImageUtils.java:42) ~[ScreenInMC.jar:?]        at cn.mingbai.ScreenInMC.Main.onEnable(Main.java:219) ~[ScreenInMC.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-163]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-163]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-163]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-163]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-163]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-163]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-163]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-163]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-163]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:51:22 INFO]: [ScreenInMC] Disabling ScreenInMC v2.0

**Comment by GZY-mingbai** [comment]
见#6

**Comment by innovateplus** [comment]
> 见#6

看了，我的是云服务器没有opencl，下载安装的是release里的2.0版本，还是要报错。

**Comment by GZY-mingbai** [comment]
在提交(99b2921)中，我修复了该BUG，只需从GitHub Releases或蓝奏云重新下载即可

**Comment by innovateplus** [comment]
感谢，成功了
